image: karelbemelmans/pipelines-hugo

pipelines:
  default:
    - step:
        script:
          - hugo --theme=hugo-orbit-theme
          - aws s3 sync --delete public s3://aws-website-jeffsinclaironline-1ezxy