# Page settings

baseurl = "https://jeffsinclair.online/"
languageCode = "en-us"
title = "Jeff Sinclair Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-66649205-3"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    title = "Jeff Sinclair - Experienced Product Leader"
    description = "Jeff Sinclair's Resume"
    author = "Jeff Sinclair"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Jeff Sinclair"
        tagline = "Product Leader"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/jefferysinclair"
        title = "Jeff Sinclair"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/jsinks"
        title = "github.com/jsinks"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/jsinkers"
        title = "@jsinkers"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Bachelor of Information Technology"
        college = "University of Technology, Sydney"
        dates = "2004 - 2006"

        [[params.education.list]]
        degree = "AWS Certified Solutions Architect - Associate"
        college = "Amazon Web Services"
        dates = "2016"

        [[params.education.list]]
        degree = "AWS Certified Developer - Associate"
        college = "Amazon Web Services"
        dates = "2016"

        [[params.education.list]]
        degree = "Certified Pragmatic Marketer Level 1 + 2"
        college = "Pragmatic Marketing"
        dates = "2016"

        [[params.education.list]]
        degree = "Agile Development with Jira Software"
        college = "Atlassian"
        dates = "2016"

         [[params.education.list]]
        degree = "Android Basics Nanodegree"
        college = "Udacity"
        dates = "2016"

         [[params.education.list]]
        degree = "Data Analyst Nanodegree"
        college = "Udacity"
        dates = "2017 - 2018"

    # Languages section
    [params.languages]
        enable = true
        title = "Languages"

        [[params.languages.list]]
        language = "English"
        level = "Native"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Product"

        [[params.interests.list]]
        interest = "Product Design"

        [[params.interests.list]]
        interest = "Big Data"
        
        [[params.interests.list]]
        interest = "Machine Learning"
        
        [[params.interests.list]]
        interest = "Software Engineering"    

        [[params.interests.list]]
        interest = "Robotics"

        [[params.interests.list]]
        interest = "Video Games"

        [[params.interests.list]]
        interest = "Home Improvement"

# Main body sections

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "Data Driven, growth-minded SaaS technology leader with over 10 years hands-on experience in both Software Development and Finance at high growth companies. I have a desirably unique blend of skills - a user-centric product mindset, a background in software engineering, advanced data exploration and analysis skills, and sharp business acumen - allowing me to step into any role and have near-immediate impact."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Professional Experience"

        [[params.jobs.list]]
        position = "Product Manager, Engagement Platform"
        dates = "2016 - Present"
        company = "Atlassian (San Francisco, USA)"
        details = "Product Manager, responsible for building Atlassian's Engagement Platform product and capability from the ground up. Responsibilities included: \n\n * Lead team of engineers and analysts to create an bespoke user messaging platform \n * Set vision and define strategy for the product team \n * Sell vision of platform to senior leadership team around company to secure funding for team \n * Participate in all key scrum-team rituals such as sprint planning and retrospectives \n * Drive adoption of the platform across Atlassian's product portfolio \n * Work with product and marketing teams to inform messaging strategy for user activation, engagement, retention, and winback of Atlassian's cloud products"

        [[params.jobs.list]]
        position = "Senior Manager, Go to Market Technology"
        dates = "2015 - 2016"
        company = "Atlassian (San Francisco, USA)"
        details = "Leader of the Go to Market Technology (IT) team, responsible for the portfolio of products and systems necessary to operate Atlassian's Marketing and Sales business units. \n  \n Responsibilities included: \n  \n * Directly manage 2 IT product managers - one algined to each business unit (MarTech and SalesTech) \n * Hire and manage day-to-day performance of these individuals, and assist in hiring of their respsective teams \n * Assist product leaders set their individual product visions and strategies \n * Key member of IT leadership team, representing the needs of my sub-teams \n * Represent teams at quarterly and yearly planning cycles for budgeting, performance reviews and talent management \n * Work extensively with related SaaS vendors for contract negotiation and ongoing management \n * Work directly with a range of internal Atlassian staff in our supported business areas \n * Dive deep to assist engineers and business analysts in my sub-teams with high impact business problems"

        [[params.jobs.list]]
        position = "IT Portfolio Manager"
        dates = "2013 - 2015"
        company = "Atlassian (San Francisco, USA)"
        details = "Acted as a senior member of the IT leadership team within Atlassian, working directly with members of the Atlassian executive team to set IT strategy and direction, and both worked with engineers and led analysts to execute on that strategy."

        [[params.jobs.list]]
        position = "Business Analyst Team Lead"
        dates = "2012 - 2013"
        company = "Atlassian (San Francisco, USA)"
        details = "Led a team of 5 Business Analysts focused on all aspects of IT capability within Atlassian. Covering all business functions and capabilities from order forms on our customer facing website, through legal and HR systems in our back office teams."

        [[params.jobs.list]]
        position = "Technical Systems Analyst"
        dates = "2011 - 2012"
        company = "Macquarie Holdings (New York, USA)"
        details = "Technical Business Analyst + Project manager for middle and back office trading systems, supporting the low / medium / high frequency proprietary trading desks. Primarily supporting the Stock Borrow/Loan capability for the High Frequency, algorithmic trading desk."

        [[params.jobs.list]]
        position = "Business Analyst"
        dates = "2010 - 2011"
        company = "Macquarie Group (Bristol, UK)"
        details = "Relocated to Bristol (United Kingdom), to work as a Business Analyst on Macquarie's UK Wrap product. Servicing independent financial advisers in the South West of the UK, with a technology platform to facilitate relationships with high net-worth clients."

        [[params.jobs.list]]
        position = "Business Analyst Team Lead"
        dates = "2009 - 2010"
        company = "Macquarie Bank (Sydney, Australia)"
        details = "Repsonsible for line management of a team of 14 Business Analysts working within the Banking + Financial Service division, in addition to my standard responsibilities as a Senior Business Analyst. Team responsible for analysis across the Credit Cards, Online Savings and Online Investment business lines. Led analysis efforts on the launch of the Macquarie Edge online trading platform."

        [[params.jobs.list]]
        position = "Business Analyst"
        dates = "2006 - 2009"
        company = "Macquarie Bank (Sydney, Australia)"
        details = "Worked for Macquarie Private Wealth as a business analyst on a number of core initiatives. Handled projects across CRM, Order Settlement, Order Management, Online Trading UI, Contract Note Fulfilment, IPO Processing, Lead Managememt, and Compliance Systems. Refined and improved existing SDLC processes for Business Analyst team."


    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"


        # Advanced skills - 8

        [[params.skills.list]]
        skill = "Atlassian products"
        level = "100%"

        [[params.skills.list]]
        skill = "Messaging strategy"
        level = "95%"

        [[params.skills.list]]
        skill = "User segmentation"
        level = "95%"

        [[params.skills.list]]
        skill = "SQL"
        level = "95%"

        [[params.skills.list]]
        skill = "Agile methodology"
        level = "95%"

        [[params.skills.list]]
        skill = "User story mapping"
        level = "90%"

        [[params.skills.list]]
        skill = "Experimentation"
        level = "85%"

        [[params.skills.list]]
        skill = "Product management"
        level = "80%"


        # Strong skills - 7

        [[params.skills.list]]
        skill = "User behaviour modelling"
        level = "75%"

        [[params.skills.list]]
        skill = "Vision & strategy"
        level = "65%"
                
        [[params.skills.list]]
        skill = "People leadership"
        level = "65%"

        [[params.skills.list]]
        skill = "Vendor management"
        level = "65%"

        [[params.skills.list]]
        skill = "Python development"
        level = "60%"   

        [[params.skills.list]]
        skill = "Public speaking"
        level = "60%"

        [[params.skills.list]]
        skill = "CI / CD"
        level = "55%"


        # Novice skills - 5

        [[params.skills.list]]
        skill = "User research"
        level = "45%"

        [[params.skills.list]]
        skill = "UX design"
        level = "45%"

        [[params.skills.list]]
        skill = "Amazon Web Services"
        level = "40%"

        [[params.skills.list]]
        skill = "Git"
        level = "35%"

        [[params.skills.list]]
        skill = "Machine learning"
        level = "30%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Jeff Sinclair"